name:                beam-times
version:             0.1.0.0
author:              "Arjun Kathuria"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Benchmarks for various DB libraries, including Beam

dependencies:
- base >= 4.7 && < 5
- text
- mysql-simple
- beam-core
- beam-mysql
- mysql-haskell
- time

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src
  dependencies:
    - scientific

executables:
  beam-times-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -rtsopts
    dependencies:
    - beam-times
    - beam-mysql

benchmarks:
  query-bench:
    main:                Main.hs
    ##type:                exitcode-stdio-1.0
    source-dirs:         bench
    dependencies:
      - criterion
      - beam-times
      - text
      - deepseq
      
tests:
  beam-times-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -rtsopts
    dependencies:
    - beam-times
